### ISSUE TITLE
javax.mail.AuthenticationFailedException

### ISSUE THREAD

**Issue by arifNislam** [luongvo/GmailBackground#10]
Hi,

A few days ago I could sent email successfully, But today I found that email is not sent and `withOnFailCallback` is called. I can log in to the email from browser.
Here is the StackTrace:
```
03-29 16:59:47.998 27019-27522/co.ppspay.paye W/System.err: javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvz
03-29 16:59:47.998 27019-27522/co.ppspay.paye W/System.err: 534-5.7.14 gInpwdhUqwU_e18KKkMlCvDrRWzlMu7IiBBn2OjNbjQdClLmMdWIx92Bii2hkEYJ-IoD-W
03-29 16:59:47.999 27019-27522/co.ppspay.paye W/System.err: 534-5.7.14 v6iF3zqDMnKuhuGbnCf6qUNePIaRHSGpHEvm4AhxfgqpKkiHAgon9LgzWbtuSKNU-h5NLu
03-29 16:59:47.999 27019-27522/co.ppspay.paye W/System.err: 534-5.7.14 aoF57c8fEYsfA31KjuZRjYQ5hZYM66cIWb3lAQLrbBTQEhGJ6_YFyPkumvtE69NUqoWqNA
03-29 16:59:47.999 27019-27522/co.ppspay.paye W/System.err: 534-5.7.14 E7O9lc2ZeqybDOEmeJx8H8J_U3lA8> Please log in via your web browser and
03-29 16:59:47.999 27019-27522/co.ppspay.paye W/System.err: 534-5.7.14 then try again.
03-29 16:59:47.999 27019-27522/co.ppspay.paye W/System.err: 534-5.7.14  Learn more at
03-29 16:59:47.999 27019-27522/co.ppspay.paye W/System.err: 534 5.7.14  https://support.google.com/mail/answer/78754 v3-v6sm1065317itb.42 - gsmtp
03-29 16:59:48.000 27019-27522/co.ppspay.paye W/System.err:     at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
03-29 16:59:48.000 27019-27522/co.ppspay.paye W/System.err:     at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)
03-29 16:59:48.000 27019-27522/co.ppspay.paye W/System.err:     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)
03-29 16:59:48.000 27019-27522/co.ppspay.paye W/System.err:     at javax.mail.Service.connect(Service.java:388)
03-29 16:59:48.000 27019-27522/co.ppspay.paye W/System.err:     at javax.mail.Service.connect(Service.java:246)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at javax.mail.Service.connect(Service.java:195)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at javax.mail.Transport.send0(Transport.java:254)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at javax.mail.Transport.send(Transport.java:124)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at com.creativityapps.gmailbackgroundlibrary.util.GmailSender.sendMail(GmailSender.java:102)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:326)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:301)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-29 16:59:48.001 27019-27522/co.ppspay.paye W/System.err:     at java.lang.Thread.run(Thread.java:760)
```

**Comment by luongvo** [comment]
@arifNislam Maybe this account is 2-auth layers activated, so it could not be used to login and send email with this lib, more https://support.google.com/mail/answer/78754
