### ISSUE TITLE
Mail not send

### ISSUE THREAD

**Issue by vagrawal1002** [luongvo/GmailBackground#5]
email is not send. It shows error "ops error sending mail"

**Comment by luongvo** [comment]
@vagrawal1002 plz send me your error log in logcat

**Comment by nvandervoort** [comment]
@luongvo I'm having the same problem, here is the Log for the error part that occurs:

```
01-17 19:11:14.240 9990-14588/com.capstone.unid.unidscanner W/System.err: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
01-17 19:11:14.240 9990-14588/com.capstone.unid.unidscanner W/System.err:   nested exception is:
01-17 19:11:14.240 9990-14588/com.capstone.unid.unidscanner W/System.err: 	java.net.SocketException: Network is unreachable
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at javax.mail.Service.connect(Service.java:388)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at javax.mail.Service.connect(Service.java:246)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at javax.mail.Service.connect(Service.java:195)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at javax.mail.Transport.send0(Transport.java:254)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at javax.mail.Transport.send(Transport.java:124)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.creativityapps.gmailbackgroundlibrary.util.GmailSender.sendMail(GmailSender.java:102)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:326)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:301)
01-17 19:11:14.334 9990-14588/com.capstone.unid.unidscanner W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.lang.Thread.run(Thread.java:762)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err: Caused by: java.net.SocketException: Network is unreachable
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.net.Socket.connect(Socket.java:586)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at java.net.Socket.connect(Socket.java:535)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:331)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:217)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
01-17 19:11:14.335 9990-14588/com.capstone.unid.unidscanner W/System.err: 	... 15 more
```

This is on a real device, not the emulator (emulator works).

**Comment by vagrawal1002** [comment]
@luongvo this is my logcat error


01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv6
01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: 534-5.7.14 DQ40RQTkYR7rKr0z53HxsJwrWz0P6oHUmpnALlKA2EqYtu01kVkZu9i59cfS2JfLDruDW_
01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: 534-5.7.14 4R1Ms_xA27LilKpI-rrrHhaw2ym8D-Dk4NiGiii0fhm9FkvWqgUGpx2xmujg4iGJFQezFj
01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: 534-5.7.14 0_oVwYNBlznXjThsfch33Ax7taJFQM0izQu3Xq7iUJgzZ7_qXmyHfyfdK6ZJ3wBiV3k-2Y
01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: 534-5.7.14 QdoTNJQzHPn0AyXLHVHCRHB9JYSJU> Please log in via your web browser and
01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: 534-5.7.14 then try again.
01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: 534-5.7.14  Learn more at
01-26 00:06:08.117 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err: 534 5.7.14  https://support.google.com/mail/answer/78754 e189sm14997239pfa.4 - gsmtp
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at javax.mail.Service.connect(Service.java:388)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at javax.mail.Service.connect(Service.java:246)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at javax.mail.Service.connect(Service.java:195)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at javax.mail.Transport.send0(Transport.java:254)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at javax.mail.Transport.send(Transport.java:124)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at com.creativityapps.gmailbackgroundlibrary.util.GmailSender.sendMail(GmailSender.java:102)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:326)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:301)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
01-26 00:06:08.123 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-26 00:06:08.124 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
01-26 00:06:08.124 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-26 00:06:08.124 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-26 00:06:08.124 31887-31981/com.intelisenze.mastersofcomputerapplications.mumca W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by aleksandrmozgovoi** [comment]
On the emulator Nox (bignox.com) API 19 onFail. Why?

W/System.err: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
W/System.err:   nested exception is:
W/System.err: 	javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2120)
W/System.err:     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
W/System.err:     at javax.mail.Service.connect(Service.java:388)
W/System.err:     at javax.mail.Service.connect(Service.java:246)
W/System.err:     at javax.mail.Service.connect(Service.java:195)
W/System.err:     at javax.mail.Transport.send0(Transport.java:254)
W/System.err:     at javax.mail.Transport.send(Transport.java:124)
W/System.err:     at com.creativityapps.gmailbackgroundlibrary.util.GmailSender.sendMail(GmailSender.java:102)
W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:326)
W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:301)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:409)
W/System.err:     at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:598)
W/System.err:     at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:372)
W/System.err:     at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:217)
W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
W/System.err: 	... 15 more
W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:611)
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
W/System.err: 	... 19 more
W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err: 	... 24 more

Internet access is available.

On a real device sending works.

**Comment by aleksandrmozgovoi** [comment]
@luongvo

**Comment by luongvo** [comment]
@aleksandrmozgovoi ok, I will spend the time to check it at the end of this working day

**Comment by aleksandrmozgovoi** [comment]
@luongvo thanks. On Android 7 also happens onFail (((

**Comment by vagrawal1002** [comment]
@luongvo any updates?

**Comment by aleksandrmozgovoi** [comment]
@luongvo 
there are results?

**Comment by techvasanth** [comment]
Please note we need to change gmail accounts security setting for the sending mails through this library. Switch on to "Less secure app access". Till then it will show error or failure. Thanking luongvo for this library.
