### ISSUE TITLE
Unable to send email because of some authentication issue 

### ISSUE THREAD

**Issue by zeeshanaslam78** [luongvo/GmailBackground#6]
I am getting this exception. It looks like there is some authentication error. I've tried to login via browser with url that is given below but It still gives same exception. I've also tried by turning off this "allow less secure apps to access your account" but still doesn't work

> javax.mail.AuthenticationFailedException: https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=Aklkjlkjlkjfdlgjsdflsdfasfweuhfwuehfuwehfuwheuhweufhuehfwuehfwuehfuwhefuhauwheufhwauefhuwhefawhfeaufhweu1uIAqs 
Please log in via your web browser and
then try again.
Learn more at
https://support.google.com/mail/answer/78754 p72sm9897983wme.17 - gsmtp
 at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:9
 at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)
 at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)
 at javax.mail.Service.connect(Service.java:388)
 at javax.mail.Service.connect(Service.java:246)
 at javax.mail.Service.connect(Service.java:195)
 at javax.mail.Transport.send0(Transport.java:254)
 at javax.mail.Transport.send(Transport.java:124)
 at com.creativityapps.gmailbackgroundlibrary.util.GmailSender.sendMail(GmailSender
 at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBack
 at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBack
 at android.os.AsyncTask$2.call(AsyncTask.java:305)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:761)

**Comment by luongvo** [comment]
@zeeshanaslam78 Did you try to enable google less secure apps? https://www.google.com/settings/security/lesssecureapps

**Comment by zeeshanaslam78** [comment]
Thanks after enabling less secure apps Its working.
