### ISSUE TITLE
Unable to Send Email on Tablets

### ISSUE THREAD

**Issue by nicemak** [luongvo/GmailBackground#7]
Hi, when i am using my mobile which is on Oreo, email is sending perfectly, but when i use same app on tablet which 4.2.1 and 5.0.1 email is not sending. please see the logcat.

02-09 11:40:30.128 6620-6640/com.expertizesolution.mak.shellproject I/System.out: Match Mom Check
02-09 11:40:30.139 6620-6640/com.expertizesolution.mak.shellproject I/System.out: [socket][0] connection smtp.gmail.com/2a00:1450:400c:c04::6d:465;LocalPort=57100(0)
02-09 11:40:30.139 6620-6640/com.expertizesolution.mak.shellproject I/System.out: [CDS]connect[smtp.gmail.com/2a00:1450:400c:c04::6d:465] tm:90
02-09 11:40:30.142 6620-6640/com.expertizesolution.mak.shellproject D/Posix: [Posix_connect Debug]Process com.expertizesolution.mak.shellproject :465 
02-09 11:40:30.158 6620-6620/com.expertizesolution.mak.shellproject V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810500
02-09 11:40:30.158 6620-6620/com.expertizesolution.mak.shellproject V/InputMethodManager: START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{25fa7113 V.E..... R.....I. 0,0-1024,600} ic=null tba=android.view.inputmethod.EditorInfo@b4d1cde controlFlags=#104
02-09 11:40:30.169 6620-6640/com.expertizesolution.mak.shellproject I/System.out: [socket][1:57100] exception
02-09 11:40:30.170 6620-6640/com.expertizesolution.mak.shellproject I/System.out: [CDS]close[57100]
02-09 11:40:30.174 6620-6641/com.expertizesolution.mak.shellproject D/GraphicBuffer: register, handle(0xac27f760) (w:1024 h:600 s:1024 f:0x1 u:0x000f02)
02-09 11:40:30.177 6620-6640/com.expertizesolution.mak.shellproject W/System.err: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
02-09 11:40:30.177 6620-6640/com.expertizesolution.mak.shellproject W/System.err:   nested exception is:
02-09 11:40:30.177 6620-6640/com.expertizesolution.mak.shellproject W/System.err: 	java.net.ConnectException: failed to connect to smtp.gmail.com/2a00:1450:400c:c04::6d (port 465) after 90000ms: isConnected failed: ENETUNREACH (Network is unreachable)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Service.connect(Service.java:388)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Service.connect(Service.java:246)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Service.connect(Service.java:195)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Transport.send0(Transport.java:254)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Transport.send(Transport.java:124)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.creativityapps.gmailbackgroundlibrary.util.GmailSender.sendMail(GmailSender.java:102)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:326)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:301)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-09 11:40:30.178 6620-6640/com.expertizesolution.mak.shellproject W/System.err: Caused by: java.net.ConnectException: failed to connect to smtp.gmail.com/2a00:1450:400c:c04::6d (port 465) after 90000ms: isConnected failed: ENETUNREACH (Network is unreachable)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:267)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:127)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:461)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.net.Socket.connect(Socket.java:918)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at java.net.Socket.connect(Socket.java:844)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:331)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:217)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
02-09 11:40:30.182 6620-6640/com.expertizesolution.mak.shellproject W/System.err: 	... 15 more
02-09 11:40:30.183 6620-6640/com.expertizesolution.mak.shellproject W/System.err: Caused by: android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
02-09 11:40:30.183 6620-6640/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:252)
02-09 11:40:30.183 6620-6640/com.expertizesolution.mak.shellproject W/System.err: 	... 24 more
02-09 11:40:30.186 6620-6620/com.expertizesolution.mak.shellproject I/System.out: Failed
02-09 11:40:30.208 6620-6649/com.expertizesolution.mak.shellproject D/libc-netbsd: [getaddrinfo]: hostname=smtp.gmail.com; servname=(null); cache_mode=(null), netid=0; mark=0
02-09 11:40:30.208 6620-6649/com.expertizesolution.mak.shellproject D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
02-09 11:40:30.208 6620-6649/com.expertizesolution.mak.shellproject D/libc-netbsd: [getaddrinfo]: hostname=smtp.gmail.com; servname=(null); cache_mode=(null), netid=0; mark=0
02-09 11:40:30.208 6620-6649/com.expertizesolution.mak.shellproject D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
02-09 11:40:30.209 6620-6649/com.expertizesolution.mak.shellproject D/libc-netbsd: [getaddrinfo]: hostname=smtp.gmail.com; servname=(null); cache_mode=(null), netid=0; mark=0
02-09 11:40:30.209 6620-6649/com.expertizesolution.mak.shellproject D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
02-09 11:40:30.209 6620-6649/com.expertizesolution.mak.shellproject I/System.out: Match Mom Check
02-09 11:40:30.212 6620-6649/com.expertizesolution.mak.shellproject I/System.out: [socket][1] connection smtp.gmail.com/2a00:1450:400c:c04::6d:465;LocalPort=50375(0)
02-09 11:40:30.217 6620-6649/com.expertizesolution.mak.shellproject I/System.out: [CDS]connect[smtp.gmail.com/2a00:1450:400c:c04::6d:465] tm:90
02-09 11:40:30.219 6620-6649/com.expertizesolution.mak.shellproject D/Posix: [Posix_connect Debug]Process com.expertizesolution.mak.shellproject :465 
02-09 11:40:30.220 6620-6649/com.expertizesolution.mak.shellproject I/System.out: [socket][2:50375] exception
02-09 11:40:30.220 6620-6649/com.expertizesolution.mak.shellproject I/System.out: [CDS]close[50375]
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:   nested exception is:
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err: 	java.net.ConnectException: failed to connect to smtp.gmail.com/2a00:1450:400c:c04::6d (port 465) after 90000ms: isConnected failed: ENETUNREACH (Network is unreachable)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Service.connect(Service.java:388)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Service.connect(Service.java:246)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Service.connect(Service.java:195)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Transport.send0(Transport.java:254)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at javax.mail.Transport.send(Transport.java:124)
02-09 11:40:30.221 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.creativityapps.gmailbackgroundlibrary.util.GmailSender.sendMail(GmailSender.java:102)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:326)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.creativityapps.gmailbackgroundlibrary.BackgroundMail$SendEmailTask.doInBackground(BackgroundMail.java:301)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err: Caused by: java.net.ConnectException: failed to connect to smtp.gmail.com/2a00:1450:400c:c04::6d (port 465) after 90000ms: isConnected failed: ENETUNREACH (Network is unreachable)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:267)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:127)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:461)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.net.Socket.connect(Socket.java:918)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at java.net.Socket.connect(Socket.java:844)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:331)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:217)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
02-09 11:40:30.222 6620-6649/com.expertizesolution.mak.shellproject W/System.err: 	... 15 more
02-09 11:40:30.223 6620-6649/com.expertizesolution.mak.shellproject W/System.err: Caused by: android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
02-09 11:40:30.223 6620-6649/com.expertizesolution.mak.shellproject W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:252)
02-09 11:40:30.223 6620-6649/com.expertizesolution.mak.shellproject W/System.err: 	... 24 more
02-09 11:40:30.223 6620-6620/com.expertizesolution.mak.shellproject I/System.out: Failed

**Comment by nicemak** [comment]
02-09 15:16:59.082 12449-12478/com.expertizesolution.mak.shellproject I/System.out: Match Mom Check
02-09 15:16:59.085 12449-12478/com.expertizesolution.mak.shellproject I/System.out: [socket][1] connection smtp.gmail.com/2a00:1450:400c:c02::6d:465;LocalPort=55609(0)
02-09 15:16:59.086 12449-12478/com.expertizesolution.mak.shellproject I/System.out: [CDS]connect[smtp.gmail.com/2a00:1450:400c:c02::6d:465] tm:90
02-09 15:16:59.089 12449-12478/com.expertizesolution.mak.shellproject I/System.out: [socket][2:55609] exception
02-09 15:16:59.089 12449-12478/com.expertizesolution.mak.shellproject I/System.out: [CDS]close[55609]
02-09 15:16:59.091 12449-12449/com.expertizesolution.mak.shellproject I/System.out: Failed
